### ISSUE TITLE
Weird behavior for installing with pip

### ISSUE THREAD

**Issue by uekerman** [precice/python-bindings#21] opened 2020-01-21 17:05 UTC
When installing with pip, I get:
```
uekerman@gauss ~/Repos/python-bindings (git)-[develop] % pip3 install --user .
Processing /home/uekerman/Repos/python-bindings
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-37sqpqlq-build/setup.py", line 12, in <module>
        from packaging import version
    ModuleNotFoundError: No module named 'packaging'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-37sqpqlq-build/
```

After `pip3 install packaging` (why doesn't this happen automatically?):
```
ERROR: fenics-adapter 0.1 requires fenics, which is not installed.
```
... but the python bindings should be independent of the FEniCS adapter.

I can successfully install with `python3 setup.py install --user`.

**Comment by IshaanDesai** [comment] 2020-01-21 20:12
Hi @uekerman unfortunately I am unable to reproduce this error on my system. I also separately tried to install `packaging` and it was installed successfully, although I needed the `--user` flag to successfully install it. Could you tell me your `pip` version?

**Comment by uekerman** [comment] 2020-01-22 08:09
I guess my `pip` system could be messed up a bit. It did neither work for the old python bindings. My `pip` version is `20.0.1`.
But that FEniCS dependency is really weird, right?

**Comment by IshaanDesai** [comment] 2020-01-22 13:25
I am looking for the dependency on FEniCS but finding it hard to get it. Meanwhile to further see if your `pip` installation is broken can you try to run `pip3 install --user -v .` and pass the output to a log file? That would give much more information. 
I am using `pip` version `19.3.1`

**Comment by uekerman** [comment] 2020-01-22 16:48
Sure, [pip.log](https://github.com/precice/python-bindings/files/4098538/pip.log)

**Comment by BenjaminRueth** [comment] 2020-01-27 08:56
The `packaging` problem also shows up in our systemtests if we use Ubuntu 18.04 (see https://github.com/precice/systemtests/pull/160).

**Comment by BenjaminRueth** [comment] 2020-02-13 09:57
I think that the problem was due to using an old pip version and/or `packaging` not being specified as build-time dependency in `pyproject.toml`. I added a [note](https://github.com/precice/python-bindings#installing-the-package) on the recommended pip version in the documentation and throw a [warning](https://github.com/precice/python-bindings/blob/c03e39220bebd3fdd32984e3ccea10bbd2888900/setup.py#L7-L9), if pip is older than recommended. If `packaging` is not installed the versions cannot be compared, but I assume that there is no way around this problem.

Closing this issue, since I think it is solved. Feel free to reopen it, if something is still unsolved.

**Closed by BenjaminRueth** 2020-02-13 09:57 UTC
Labels: bug, documentation
