### ISSUE TITLE
Versioning of Python bindings

### ISSUE THREAD

**Issue by fsimonis** [precice/python-bindings#6] opened 2019-12-03 09:55 UTC
Now that we decoupled the python bindings from preCICE, we will have to deal with the versioning.
We already use semantic versioning for both preCICE and the python bindings, so we should stick with it.

The major and minor versions of preCICE include interface changes that need to be reflected in the python bindings.
The patch version of preCICE does not influence the python bindings. so we could use it for versioning the python bindings themselves.

So I propose the following version scheme for the bindings:

| | Major | Minor | Patch |
--- | --- | --- | ---
**preCICE** | Breaking Changes | Additions | Bugfixes of preCICE
**bindings** | Breaking Changes | Additions  | Bugfixes of bindings

**Comment by uekerman** [comment] 2020-01-07 22:03
> The major and minor versions of preCICE include interface changes that need to be reflected in the python bindings.

Why the minor versions as well? There could be functionality added, yes, but no breaking changes.

**Comment by fsimonis** [comment] 2020-01-08 18:34
@uekerman if we don't use the minor version, newer bindings can break with older versions due to missing functions in the interface.

Bindings are compatible with the same major version and greater equal minor version of precice as they may implement a subset of functions, but require all used functions to be present.

**Comment by uekerman** [comment] 2020-01-09 09:07
I suggest to keep the discussion what we want to do in the dev mailing list as we have already more content there and describe here only the final solution we want to implement.

**Comment by BenjaminRueth** [comment] 2020-02-10 15:40
Closed as duplicate of #31

**Closed by BenjaminRueth** 2020-02-10 15:40 UTC
